
// "": {
//   name: "",
//   ingredients: {"": ""},
//   instructions: [""],
//   notes: [""],
// },

const lunch = {
  "Chicken-Fried-Rice": {
    name: "Chicken Fried Rice",
    ingredients: {
      "chicken breast, diced": "3/4 - 1 lb",
      butter: "4-8 tbsp",
      "sesame oil": "2 tbsp",
      "onion, chopped small": 1,
      "peas and carrots, frozen mix": "1 1/3 cups",
      "green onions, chopped": "3",
      "garlic, minced": "2 cloves",
      eggs: "2",
      "rice, cooked": "3 cups",
      "soy-sauce": "3 tbsp",
      "salt and pepper": "To taste",
    },
    instructions: [
      "Heat butter over medium-high heat, add chicken once hot",
      "Season with salt and pepper and saute until cooked through, about 5-6 minutes",
      "Transfer chicken to a plate and set aside",
      "Add half of the sesame oil to the pan. Once hot add onion and caramelize",
      "Add remaining sesame oil, peas and carrots, saute 1 minute",
      "Add garlic and saute 1 minute longer",
      "Push veggies to the side, add eggs and scramble",
      "Return the chicken, add rice and soy sauce. Season to taste",
      "Heat and stir 1-2 minutes until combined",
      "Serve and enjoy!",
    ],
    notes: ["I usually skip the peas and carrots"],
  },
  'Shrimp-Scampi' : {
    name: "Shrimp Scampi",
    ingredients: {"olive oil": "2 tablespoons",
  'butter': '4 tablespoons',
  'garlic': '4-5 cloves',
  'large shrimp': '1 1/4 lbs',
  'salt and pepper': 'To taste',
  'dry white wine': '1/4 cup',
  'crushed red pepper flakes': '1/2 teaspoon',
  'lemon juice': '2 tablespoons',
  'parsley, chopped': '1/4 cup'},
    instructions: ["Heat olive oil and 2 tablespoons of butter in a large pan or skillet. Add garlic and saute until fragrant (about a minute).",
  'Add shrimp, season with salt and pepper and saute for 1-2 minutes on one side until just turning pink.',
  'Flip the shrimp. Add wine and pepper flakes, simmer 1-2 minutes or until wine is reduced to about half and shrimp is cooked through.',
  'Stir in lemon juice, parsley, and remaining butter then take offf heat immediately.',
  'Serve over noodles, rice, or steamed veggies.'],
    notes: ["You can sub the wine for chicken broth"],
  },
};

const dinner = {
  "Beef-Stroganoff": {
    name: "Beef Stroganoff",
    ingredients: {
      "steak, cut into strips": "1 lb",
      "red wine": "1/2 cup",
      "unsalted butter": "8 tbsp",
      "olive oil": "2 tbsp",
      onion: 1,
      "brown mushrooms": "1/2 lb",
      "garlic, minced": "2 cloves",
      "all-purpose flour": "1 tbsp",
      "beef broth": "1 cup",
      yogurt: "1 cup",
      "worcestershire sauce": "1 tbsp",
      "dijon mustart": "1/2 tsp",
      "salt and pepper": "To taste",
      "egg noodles": "8-12 oz",
    },
    instructions: [
      "Add wine and butter to a deep pan, heat over medium-high heat. Add beef once hot",
      "Cook beef until just browned on both sides. Remove to a plate and set aside, retaining the juices",
      "Add olive oil. Once hot, add onion and cook about 5-10 minutes",
      "Add mushrooms and cook until most of the remaining liquid is gone. Onions should be caramelized and mushrooms lightly browned",
      "Add garlic, heat until fragrant",
      "Add flour, stir vigorously until combined and lumps are gone",
      "Pour in beef broth, scraping any bits from the bottom of the pan",
      "Add yogurt or creams (temper the sour cream by adding a few tablespoons of sauce to it first) and stir well. Let simmer until slightly thickened",
      "Add worcestershire sauce and mustard, season to taste. Stir until sauce is creamy",
      "Return the beef and any juices back to the pan, simmer until beef is heated through",
      "Serve over egg noodles",
    ],
    notes: [
      "You can substitute the yogurt for 1/4 cup sour cream + 3/4 cups heavy cream",
      "Serve over mashed potatos instead for a super creamy and delicious twist on a classic",
    ],
  },
  "Whole-Turkey": {
    name: "Whole Turkey",
    ingredients: {
      "whole turkey": "14 lbs",
      "olive oil": "1 tablespoon",
      sage: "1 tablespoon",
      "garlic powder": "2 teaspoons",
      paprika: "2 teaspoons",
      "salt and pepper": "To taste",
    },
    instructions: [
      "Place oven rack in lowest position. Preheat oven to 325°F",
      "Place turkey in pan breast-side up and brush with oil. Sprinkle seasoning mixture evenly over turkey. Cover loosely with heavy duty foil",
      "Roast 2 hours, adding an extra 15 minutes per pound for larger turkeys",
      "Remove foil. Roast 1 hour longer or until internal temperature in thigh reaches 165°F, basting occasionally with pan juices",
      "Remove turkey from oven. Let stand 20 minutes",
      "Transfer to platter or carving board and slice. Reserve pan juices to make gravy or to serve with turkey",
    ],
    notes: ["For easy cleanup, line roasting pan with heavy duty foil"],
  },
  "Steak-Fajitas": {
    name: "Steak Fajitas",
    ingredients: {
      "soy sauce": "1/2 cup",
      "lime juice": "1/2 cup",
      "avocado oil": "1/2 cup",
      "red wine": "1/4 cup",
      "brown sugar, packed": "1/4 cup",
      "chili powder": "1 tablespoon",
      "garlic, minced": "3 cloves",
      cumin: "2 teaspoons",
      "black pepper": "2 teaspoons",
      "steak, cut into strips": "2 pounds",
      "red, yellow, and green pepper, sliced": "1 each",
      "onion, sliced": "1",
      "corn starch": "1 tablespoon",
      "beef broth": "1/2 cup",
      "tortillas, sour cream, and shredded cheese": "For serving",
    },
    instructions: [
      "Mix the Marinade: Combine soy sauce, lime juice, avocado oil, red wine, brown sugar, chili powder, garlic, cumin, and black pepper in a medium bowl and whisk to combine. Transfer 3/4 cup (120ml) marinade to a large bowl and set aside.",
      "Place steaks in a gallon-sized zipper-lock bag and add remaining marinade. Seal bag, squeezing out as much air as possible. Massage bag until meat is fully coated in marinade. Lay flat in the refrigerator, turning every couple of hours, for at least 3 hours.",
      "Toss peppers and onion in bowl with reserved marinade. Refrigerate until ready to use.",
      "When ready to cook, pour marinade from steak into a cast iron skillet and heat.",
      "Cook beef until just browned on both sides. Remove to a plate and set aside, retaining the juices",
      "Add vegitables with marinade to pan. Cook until tender and most of the liquid has evaporated.",
      "Sprinkle the corn starch over the vegitables and stir well, avoiding clumps.",
      "Pour in beef broth, scraping any bits from the bottom of the pan",
      "Add back the beef and any accumulated juices, stir until warm.",
      "Warm tortillas for serving. Enjoy!",
    ],
    notes: [""],
  },
  "Tomato-Sauce": {
    name: "Tomato Sauce",
    ingredients: {
      tomatos: "4 lbs",
      "unsalted butter": "6 tablespoons",
      "olive oil": "4 tablespoons",
      onions: "2",
      garlic: "4 cloves",
      salt: "1 1/4 teaspoons",
      sugar: "1 teaspoon",
      basil: "2 tablespoons",
    },
    instructions: [
      "Bring a large pot of water to boil and set a side a large bowl about halfway full with ice water.",
      "Cut a 1/4 inch deep x on one end of each tomato. Place tomatos into the boiling water (I ike to use a spoon to gently place them in) and boil 1-2 minutes until the skin splits.",
      "Use a spoon to remove the tomatos from the boiling water and place them in the ice bath. Let cool 1-2 minutes, gently peel the skin with your hands and discard.",
      "Cut the tomatos into 1/2 inch chunks, discarding the cores, and transfer them to a sauce pan.",
      "Add butter, olive oil, onions, garlic, salt, and sugar to the tomatos. If using dried basil, add it now. Bring the mixture to a gentle boil, then reduce heat and simmer for 1 1/2 to 2 1/2 hours, stirring occasionally.",
      "Once the sauce is no longer wattery, strain the liquid into another pan and use a potato masher to mash any strained chunks. Add the mash back to the liquid. If using fresh basil, add it now.",
      "Season to taste and serve.",
    ],
    notes: ["Add 4 cups of chicken broth for a creamy tomato soup."],
  },
};

const sweets = {
  "Chocolate-Chip-Cookies": {
    name: "Chocolate Chip Cookies",
    ingredients: {
      "salted butter": "8 tablespoons",
      "white sugar": "1/2 cup",
      "packed light brown sugar": "1/4 cup",
      vanilla: "1 teaspoon",
      egg: 1,
      "all purpose flour": "1 1/2 cups",
      "baking soda": "1/2 teaspoon",
      salt: "1/4 teaspoon",
      "chocolate chips": "3/4 cup",
    },
    instructions: [
      "Preheat oven to 350 degrees",
      "Melt butter in microwave for 40-60 seconds",
      "Beat butter with sugars until creamy",
      "Add vanilla and egg, beat for 10-15 seconds",
      "Add flour, baking soda, and salt. Mix until dough forms",
      "Fold in the chocolate chips",
      "Roll dough into 9-12 balls and place evenly spaced on baking sheet",
      "Bake for 9-11 minutes until just golden brown on the bottom",
      "Let cool on the pan until stiff (about 30 minutes)",
      "Enjoy!",
    ],
    notes: ["Use a hand or stand mixer for the best results"],
  },
  Pancakes: {
    name: "Pancakes",
    ingredients: {
      "All-purpose flour": "1 1/2 cups",
      "baking powder": "3 1/2 teaspoons",
      sugar: "1 tablespoon",
      salt: "1/4 teaspoon",
      milk: "1 1/4 cups",
      "butter (melted)": "3 tablespoons",
      egg: 1,
    },
    instructions: [
      "Sift flour, baking powder, sugar, and salt together in a large bowl",
      "Make a well in the center, add milk, butter, and egg; mix until smooth",
      "Lightly oil griddle or pan and heat over medium-high heat",
      "Use about 1/4 cup of batter per pancake, cook 2-3 minutes until bubbles form and the edges are dry",
      "Flip and cook until browned",
      "Repeat with remaining batter, makes about 8",
    ],
    notes: [""],
  },
};

export default {
  lunch: lunch,
  dinner: dinner,
  sweets: sweets,
};